
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Apr 29 11:11:12 CEST 2015
//----------------------------------------------------

package plicCompiler.analyseLexSynt;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int CSTE = 14;
  public static final int IDF = 25;
  public static final int ECRIREIDF = 21;
  public static final int CLASSEIDF = 23;
  public static final int CHAINE = 24;
  public static final int PLUS = 9;
  public static final int SUP = 6;
  public static final int EQUAL = 8;
  public static final int END = 17;
  public static final int LIREIDF = 22;
  public static final int PUBLIC = 18;
  public static final int INF = 7;
  public static final int FAUX = 16;
  public static final int POINTVIRGULE = 2;
  public static final int PARFER = 4;
  public static final int ENTIER = 20;
  public static final int EOF = 0;
  public static final int DIV = 13;
  public static final int MINUS = 10;
  public static final int error = 1;
  public static final int VRAI = 15;
  public static final int PRIVE = 19;
  public static final int PAROUV = 3;
  public static final int DIFF = 5;
  public static final int MUL = 12;
  public static final int UMINUS = 11;
}

