
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Apr 08 18:22:55 CEST 2015
//----------------------------------------------------

package plicCompiler.analyseLexSynt;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int MINUS = 10;
  public static final int PARFER = 4;
  public static final int POINTVIRGULE = 2;
  public static final int CSTE = 13;
  public static final int EQUAL = 8;
  public static final int PAROUV = 3;
  public static final int FAUX = 15;
  public static final int PLUS = 9;
  public static final int EOF = 0;
  public static final int VRAI = 14;
  public static final int DIV = 12;
  public static final int error = 1;
  public static final int INF = 7;
  public static final int DIFF = 5;
  public static final int MUL = 11;
  public static final int SUP = 6;
}

